# Lab 1: Practice Working with NumPy and Pandas

In [1]:
import pandas as pd
import numpy as np

In this lab you will practice working with the NumPy and Pandas packages. You will:

1. Work with NumPy arrays and NumPy functions.
2. Create Pandas DataFrames from data
3. Use NumPy and Pandas to analyze the data
4. Visualize the data with Matplotlib

## Part 1. NumPy Arrays

### a. Define a new Python *list*

Let us practice defining a new list in Python:

In [2]:
my_list = [0,0,1,2,3,3,4.5,7.6]
my_list

[0, 0, 1, 2, 3, 3, 4.5, 7.6]

### b. (Two ways to) define a *range*

One type of list is a range of (e.g., integer) numbers. Ranges are useful for iterating over in a loop -- that is, to assign some variable to take on each value in this list sequentially. (For example, `i=1`, then `i=2`, then `i=3`, etc., until `i=100`.) <br>

Let's create an evenly spaced array of integers ranging from 0 to 11:

In [3]:
#First, the basic python way:
my_range = range(0,12)
my_range

range(0, 12)

In [4]:
#Now the numpy way:
my_range_np = np.arange(12)
my_range_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

You can see that the first method returns a special 'range' object, while the latter returns an object of type 'numpy array'. If we convert both to lists, they will be the same:

In [5]:
list(my_range)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [6]:
list(my_range_np)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

### c. List comprehension

Consider the task of replacing each value in a list with its square. The traditional way of performing te same transformation on every element of a list is via a `for` loop:

In [7]:
my_range_np = np.arange(12)

for i in range(0, len(my_range_np)):
    my_range_np[i] = my_range_np[i]**2 #square each element
print(my_range_np)

[  0   1   4   9  16  25  36  49  64  81 100 121]


That worked. However, there is a better, more 'Pythonic' way to do it. <br>

*List comprehension* is one of the most elegant functionalities native to Python, and is beloved by programmers like you. It offers a concise way of applying a particular transformation to every element in a list. <br>

Using list comprehension syntax, we can write a single, easily interpretable line that does the same transformation without using ranges, nor do we have to introduce an iterating index variable `i`:

In [8]:
my_range_np = np.arange(12)

my_range_np = [x**2 for x in my_range_np]
my_range_np

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]

### d. Creating a one-dimensional NumPy *array*. 

Let's explicitly create a one-dimensional `numpy` array (as opposed to a list):

In [9]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

### e.  Retrieving the dimensions of data structure:  len() and np.shape()

How would we go about creating a variable that contains the length of our array `arr` ?<br>
We could use the Python function ```len()```... 

In [10]:
arr_length = len(arr)
arr_length

4

... or use the `numpy` function ```np.shape()```, saving only the first of the two values that it returns:

In [11]:
arr_length = np.shape(arr)[0]
arr_length

4

<b>Tip</b>: try removing the slice indicator `[0]` and see how the output changes. Notice that there appears to be an empty 'slot' for another number in the returned value pair.

### f. Creating a uniform (same value in every position) array: np.ones()

We will now use ```np.ones()``` to create an array of a pre-specified length that contains the value '1' in each position:

In [12]:
length = 55
np.ones(length, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

We can use this method to create an array of any identical values. <br>
Let's create an array of length 13, filled with the vlue '7' in every position:

In [13]:
7*np.ones(13, dtype=int)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

### g. Creating two-dimensional arrays

Exploring the possibilities of the ```np.array()``` function further, let's move on to creating not one- but two-dimensional arrays (aka matrices):

In [14]:
M = np.array([[1,2,3], [4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.shape(M)

(2, 3)

NumPy contains useful functions for creating identity matrices of a specified size:

### h. Creating an identity matrix: np.eye()

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#check your intuition: what will be the output after running this cell?
A = np.eye(3)
B = 4*np.eye(3)
A+B

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

### i. A small challenge:  matrix transformation and random matrix generation
Using the matrix ```M``` below and the function ```np.triu()```. Inspect the documentation by running the command ```np.triu?``` in the cell below. Create a matrix ```N``` which is identical to ```M``` except in the lower triangle (i.e., all the cells below the diagonal). The lower triangle should be filled with zeros.

In [18]:
np.triu?

In [19]:
M = np.round(np.random.rand(5,5),2)
print("M=\n", M)

# your code here:
N = np.triu(M)

M=
 [[0.2  0.46 0.78 0.66 0.06]
 [0.1  0.89 0.76 0.51 0.98]
 [0.58 0.8  0.2  0.87 0.08]
 [0.29 0.75 0.18 0.55 0.21]
 [0.99 0.6  0.12 0.03 0.75]]


Using the code provided above for generating the matrix ```M```, try to figure out how to create a random matrix with 13 rows and 3 columns. <br>

In [20]:
M = np.random.rand(13, 3)


### j. Indexing and slicing arrays

Here is how to call an element of a 2D array by its location (i.e., its row index and column index):

In [21]:
M[3,2]

0.17005889695850618

In [22]:
# test your intuition: what would you expect this code to return?
M[3:,2]

array([0.1700589 , 0.12635104, 0.26939184, 0.03625618, 0.6973572 ,
       0.23389716, 0.74126934, 0.95856562, 0.07862377, 0.09231905])

### k. Evaluating a Boolean condition

In real-life data tasks, you will often have to compute the boolean ```(True/False)``` value of some statement, for all entries in a list, or for a matrix column (essentially, a list), or for the entire matrix. <br>
In other words, we may want to formulate a condition -- think of it as a *test* -- and run a computation that returns `True` or `False` depending on whether the test is passed or failed by a particular value in a data structure.

For example, our test may be something like "the value is greater than 0.5", and we would like to know if this is true or false for each of the values in a list. Here's how to compute a list of values that the condition test takes for each value of a given list:

In [23]:
g = np.random.rand(1, 20) #first, create the list 
print(g)

[[0.17937505 0.79676555 0.84257748 0.86437092 0.78947135 0.7118935
  0.87977194 0.8616657  0.88519664 0.20246119 0.33434791 0.56366072
  0.81549941 0.00535101 0.72814725 0.06066362 0.14492107 0.09992011
  0.97619938 0.83508557]]


In [24]:
is_greater = g>0.5
print(is_greater)

[[False  True  True  True  True  True  True  True  True False False  True
   True False  True False False False  True  True]]


In [25]:
# Let's print the matrix M again so we can glance at it for our next exercise
print(M)

[[0.09841958 0.46308754 0.2832072 ]
 [0.01651112 0.67586352 0.41574991]
 [0.17996986 0.33537248 0.22812053]
 [0.68411624 0.33996013 0.1700589 ]
 [0.61475492 0.34893807 0.12635104]
 [0.92382496 0.06429013 0.26939184]
 [0.05210433 0.40540843 0.03625618]
 [0.64821793 0.92656108 0.6973572 ]
 [0.41545122 0.86226129 0.23389716]
 [0.62803088 0.69703549 0.74126934]
 [0.34466607 0.02640153 0.95856562]
 [0.19873275 0.24988754 0.07862377]
 [0.57054937 0.60489294 0.09231905]]


In [26]:
# What would you expect to see once you run the code below?
c_is_greater = M[:,1]>0.5
c_is_greater

array([False,  True, False, False, False, False, False,  True,  True,
        True, False, False,  True])

### L . NumPy Functions `np.any()`, `np.unique() `

We can use ```np.any()``` to determine if there is any entry in column 1 that is smaller than 0.1:

In [27]:
c_is_smaller = M[:,1]<0.1
np.any(c_is_smaller)

True

A small challenge:<br>
You have birthday data for a cohort of 100 people all born in 1990.
Given the one-dimensional array of birthdays ```random_bdays``` generated below, figure out if there exists a pair of people who share a birthday.<br>

<b>Tip</b>: you may find the function ```np.unique()``` useful. Feel free to read up on it by running the command `np.unique?` in a new cell.

In [28]:
# do not edit this code:
random_nums = np.random.choice(365, size = 100)
random_bdays = np.datetime64('1990-01-01') + random_nums

## your code here:
duplicates_exist = len(np.unique(random_bdays)) < len(random_bdays)

print("Duplicates exist:", duplicates_exist)


Duplicates exist: True


## Part 2. Pandas DataFrames

### a. Creating a DataFrame: two (of the many) ways

The code cells below demonstrate how we can create Pandas DataFrames from scratch: from a *list of lists*, and from a *dictionary*. First, the cell below creates a DataFrame from a list containing phone numbers and their country codes. The DataFrame is named `df`. Run the cell below to inspect the DataFrame `df` that was created.

In [29]:
my_list = [['+1', '(929)-000-0000'], ['+34', '(917)-000-0000'], ['+7', '(470)-000-0000']]
df = pd.DataFrame(my_list, columns = ['country_code', 'phone'])
df

country_code           phone
0           +1  (929)-000-0000
1          +34  (917)-000-0000
2           +7  (470)-000-0000

Second, the cell below creates a DataFrame from a dictionary that contains the same information as the list above. The dictionary contains phone numbers and their country codes. Run the cell below to inspect the DataFrame `df_from_dict` that was created from the dictionary. Notice that both DataFrames `df` and `df_from_dict` contain the same values.

In [30]:
my_dict = {'country_code': ['+1', '+34', '+7'], 'phone':['(929)-000-0000', '(917)-000-0000', '(470)-000-0000']}
df_from_dict = pd.DataFrame(my_dict)
df_from_dict

country_code           phone
0           +1  (929)-000-0000
1          +34  (917)-000-0000
2           +7  (470)-000-0000

### b. Adding a column to a DataFrame object

We are going to continue working with the DataFrame `df` that was created above. In the code cell below, we add a new column of values to DataFrame `df`. Run the cell and inspect the DataFrame to see the new column that was added.

In [31]:
df['grade']= ['A','B','A']
df

country_code           phone grade
0           +1  (929)-000-0000     A
1          +34  (917)-000-0000     B
2           +7  (470)-000-0000     A

### c. Sorting the DataFrame by values in a specific column: `df.sort_values()`

In [32]:
df = df.sort_values(['grade'])
df

country_code           phone grade
0           +1  (929)-000-0000     A
2           +7  (470)-000-0000     A
1          +34  (917)-000-0000     B

### d. Combining multiple DataFrames with `pd.concat()` and `pd.merge()` and renaming  columns with `df.rename()`

In real life settings, you will often need to combine separate sets of related data.<br>
To illustrate, let's create a new DataFrame. The code cell below creates a new DataFrame `df2` that also contains phone numbers, their country codes and a grade. Run the cell and inspect the new DataFrame that was created.

In [33]:
my_dict2 = {'country': ['+32', '+81', '+11'], 'grade':['B', 'B+', 'A'], 'phone':['(874)-444-0000', '(313)-003-1000', '(990)-006-0660']}
df2 = pd.DataFrame(my_dict2)
df2

country grade           phone
0     +32     B  (874)-444-0000
1     +81    B+  (313)-003-1000
2     +11     A  (990)-006-0660

The code cell below uses the Pandas ```pd.concat()``` function to append the second DataFrame to the first one. It saves the newly formed DataFrame to variable `df_concat`. Note that the `pd.concat()` function will not change the values in the original DataFrames.

In [34]:
df_concat = pd.concat([df,df2])
df_concat

country_code           phone grade country
0           +1  (929)-000-0000     A     NaN
2           +7  (470)-000-0000     A     NaN
1          +34  (917)-000-0000     B     NaN
0          NaN  (874)-444-0000     B     +32
1          NaN  (313)-003-1000    B+     +81
2          NaN  (990)-006-0660     A     +11

Notice that the new DataFrame contains redundancy caused by the different spelling of the column names that contain the country code in the two original DataFrames. This can be easily fixed. The code cell below changes the name of the column in DataFrame `df2` to be consistent with the name of the column in DataFrame `df`.

In [ ]:
df2 = df2.rename(columns={'country':'country_code'})
df2

<b>Task</b>: In the cell below, run the `pd.concat()` function again to concatenate DataFrames `df` and `df2` and save the resulting DataFrame to variable `df_concat`. Run the cell and inpect the results.

In [35]:
## your code here

print(df_concat)

  country_code           phone grade country
0           +1  (929)-000-0000     A     NaN
2           +7  (470)-000-0000     A     NaN
1          +34  (917)-000-0000     B     NaN
0          NaN  (874)-444-0000     B     +32
1          NaN  (313)-003-1000    B+     +81
2          NaN  (990)-006-0660     A     +11


One other problem is that the index has repeated values. This defeats the purpose of an index, and ought to be fixed. Let's try the concatenation again, this time adding `reset_index()` method to produce correct results:

In [ ]:
df_concat = pd.concat([df,df2]).reset_index()
df_concat

What if our task was to merge ```df2``` with yet another dataset -- one that contains additional unique columns? Let's look at DataFrame `df2` again:

In [ ]:
df2

The code cell below creates a new DataFrame `df3`.

In [ ]:
my_dict3 = {'country_code': ['+32', '+44', '+11'], 'phone':['(874)-444-0000', '(575)-755-1000', '(990)-006-0660'], 'grade':['B', 'B+', 'A'], 'n_credits': [12, 3, 9]}
df3 = pd.DataFrame(my_dict3)
df3

The next cell merges both DataFrames and applies the change to DataFrame `df2`. Feel free to consult the definition of the Pandas ```merge()``` method to better undertsand how `merge()` works.

In [ ]:
df2 = df2.merge(df3, on = 'phone')
df2

### e. Loading a dataset: `pd.read_csv()`

We are now well equipped to deal with a real dataset!<br>


For the next few exercises, our dataset will contain information about New York City listings on the Airbnb platform. Note: the cell below may generate a warning. Ignore the warning. 

In [ ]:
import os 
filename = os.path.join(os.getcwd(), "labs_data", "airbnb_lab1.csv.gz") # path to file and file name
data = pd.read_csv(filename)

In [ ]:
data.shape

First, get a peek at the data:

In [ ]:
data.head()

That's a lot of columns, and the layout is a little difficult to read. <br>
Let us retrieve just the list of column names, so we can read it and get a feeling for what kind of information is presented in the dataset.

### f. Get column names: `df.columns`

In [ ]:
list(data.columns)

What do the column names mean? Some of them are less intuitively interpretable than others. <br>
Careful data documentation is indispensable for business analytics. You can consult the documentation that accompanies this open source dataset for a detailed description of the key variable names, what they represent, and how they were generated.

### g. Summary statistics of the DataFrame: `df.describe()`

Let's print some general statistics for each one of the `data` columns:

In [ ]:
data.describe(include='all')


<br>Consider the following business question:<br>
What is the average availability (out of 365 days in a year) for the listings in Brooklyn? <br>
The answer can be obtained by the use of **filters** on the dataset.

### h. Filtering the data: `df[ < condition > ]`

We need to filter the entries that are in Brooklyn. To do this, we need to know what is the exact way that Manhattan listings are spelled and entered in the data. Let's print all of the unique values of the 'neighborhood' column:

In [ ]:
data['neighbourhood'].unique()

You may have noticed that there is a lot of heterogeneity in the way `neighborhood` values are specified. The values are not standardized. There are overlaps, redundancies, and inconsistencies (e.g., some entries specify ```'Greenpoint, Brooklyn, New York, United States'```, some other ones list `'BROOKLYN, New York, United States',`, yet other ones say `'Williamsburg, Brooklyn, New York, United States'`, etc. In real life, you would have to clean this data and replace these values with standard, identically formated, consistent values. <br>

For this data file, however, we are lucky to already have a 'cleansed' version of the neighborhood information based on the latitude and the longitude of every listing location. 

We will list the unique values of the columns titled `neighbourhood_cleansed` and `neighbourhood_group_cleansed`:

In [ ]:
data['neighbourhood_cleansed'].unique()

In [ ]:
data['neighbourhood_group_cleansed'].unique()

Great, this last one is what we want! Let's filter out all data entries that pertain to Brooklyn listings:

In [ ]:
bk = data[data['neighbourhood_group_cleansed'] == 'Brooklyn']
bk.shape

<b>Tip</b>: to better understand what happened above, you are encouraged to insert a new code cell below and copy *just the condition* of the filter that we used on the `data` object above: `data['neighbourhood_group_cleansed'] == 'Brooklyn'`. Run the new cell and see what that condition alone evaluates to. You should see a Pandas series containing True/False values. When we use that series as a Boolean filter by writing `data[ < our Boolean series > ]`, i.e `data['neighbourhood_group_cleansed'] == 'Brooklyn']` , we are telling Pandas to keep the values in the DataFrame `data` only with those indices for which the condition evaluated to `True`. 

### i. Combining values in a column: `np.mean()`

Now that we isolated only the relevant entries, it remains to average the value of a particular column that we care about:

In [ ]:
np.mean(bk['availability_365'])

### j. Group data by (categorical) column values: `df.groupby()`

The next question of interest could be:<br>
What are the top 5 most reviewed neighborhoods in New York? (By sheer number of reviews, regardless of their quality). <br>
We will use the ```groupby``` method from the Pandas package:

In [ ]:
nbhd_reviews = data.groupby('neighbourhood_cleansed')['number_of_reviews'].sum()
nbhd_reviews.head()

Perform a (descending order) sorting on this series:

In [ ]:
nbhd_reviews = nbhd_reviews.sort_values(ascending = False)
nbhd_reviews.head(5)

Success!<br>
While we re at it, what are the least reviewed neighborhoods?

In [ ]:
nbhd_reviews.tail(5)

This result makes it apparent that our dataset is somewhat messy!

Notice we could have chained the transformations above into a single command, as in:

In [ ]:
data.groupby('neighbourhood_cleansed')['number_of_reviews'].sum().sort_values(ascending = False).head(5)

This way we don't store objects that we won't need.

### Bonus: easy histogram plotting with Matplotlib: `plt.hist()`

As a final touch, run the cell below to instantly visualize the density of (average!) values of review numbers across all neighbourhoods:

In [ ]:
%matplotlib inline
nbhd_reviews.hist()

This plot suggests that the vast majority of neighborhoods have only very few reviews, with just a handful of outliers (those ranked at the top in our previous computed cell) having the number of reviews upward of 40000. 